name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn jinja2 pytest pylint black pytest-cov
          pip install sqlalchemy
          pip install torchvision torchaudio
      - name: Lint with pylint
        run: |
          pylint app || exit 1
      - name: Check code formatting with black
        run: |
          black --check app tests
      - name: Run tests
        run: |
          pytest
      - name: Check test coverage
        run: |
          pytest --cov=app --cov=tests --cov-report=term-missing --cov-fail-under=80
